template_bucket_name: !stack_output managed-project-dependencies/bucket.yaml::BucketName
role_arn: !stack_output managed-project-dependencies/role.yaml::RoleArn
notifications:
  - !stack_output managed-project-dependencies/topic.yaml::TopicArn
