AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties: {}

  Queue:
    Type: AWS::SQS::Queue
    Properties: {}

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref Topic
      Protocol: "sqs"
      Endpoint: !GetAtt Queue.Arn

Outputs:
  TopicArn:
    Value: !Ref Topic
  QueueEndpoint:
    Value: !Ref Queue
