template:
  path: dependencies/dependent_template_local_export.json

region: eu-west-1

parameters:
  DependentStackName: !stack_output_external "{project_code}-external-stack-output-outputter::StackName"
