Transform: 'AWS::Serverless-2016-10-31'

Resources:
    TestFunction2:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: python3.6
        InlineCode: "print('Hello Again World!')"