Resources:
    WaitConditionHandle:
      Type: "AWS:CloudFormation::WaitConditionHandle"
    WaitCondition:
      Type: "AWS::CloudFormation::WaitCondition"
      Properties:
        Count: 1
        Handle: !Ref WaitConditionHandle
