sceptre_user_data:
  type: AWS::CloudFormation::WaitConditionHandle
template:
  path: /Users/alexharvey/git/fox/sceptre/integration-tests/sceptre-project/templates/jinja/invalid_template_missing_attr.j2
  type: file
