template_path: dependencies/dependent_template_local_export.json
region: eu-west-1
parameters:
  DependentStackName: !stack_output_external "sceptre-integration-tests-b977d03a27d611ecbbdeacde48001122-9-A::StackName default::eu-west-1"
