# The idea with this workflow is to allow core reviewers to trigger the
# integration tests by pushing a branch to the sceptre repository.
name: branch-integration-tests

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  code-changes:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - 'tests/**'
              - 'sceptre/**'
              - 'integration-tests/**'
              - 'pyproject.toml'
              - 'poetry.lock'
              - 'Dockerfile'
              - '.github/workflows/*integration-tests.yaml'

  integration-tests:
    needs: code-changes
    if: ${{ github.ref != 'refs/heads/master' && needs.code-changes.outputs.python == 'true' }}
    uses: "./.github/workflows/integration-tests.yaml"
    with:
      # role generated from https://github.com/Sceptre/sceptre-aws/blob/master/config/prod/gh-oidc-sceptre-tests.yaml
      role-to-assume: "arn:aws:iam::743644221192:role/gh-oidc-sceptre-tests"
