name: staging

on:
  workflow_run:
    workflows:
      - tests
      - integration-tests
    branches:
      - master
    types:
      - completed

jobs:
  docker-build-push:
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push Docker image to sceptreorg/sceptre:${{ steps.meta.outputs.tags }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sceptreorg/sceptre:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
